"""Type stub of the native module `mp305._native` (the Rust crate `mp305-py`).

Implements: DD-PY-061.
"""

import os
from collections.abc import Callable
from pathlib import Path
from typing import final

from mp305.testing import ScriptDict

__all__ = [
    "SCAN_DEFAULT_S",
    "SCAN_MIN_S",
    "SCAN_MAX_S",
    "WAIT_SLICE_S",
    "SUPPLY_MAX_RAW_VOLTAGE",
    "SUPPLY_MAX_RAW_CURRENT",
    "MOCK_HOST_ID",
    "Session",
    "MockHandles",
    "discover",
    "not_found_text",
    "csv_header",
    "format_csv_row",
    "raw_voltage",
    "raw_current",
    "setpoint_range_text",
    "default_state_dir",
    "host_id",
    "set_gate",
    "log_wait",
    "log_test",
    "pending_safety",
    "wait_safety",
    "fixtures",
    "c3",
    "on_air",
    "sample_events",
]

# The tuple aliases below exist only in this stub (DD-PY-061);
# tests/unit/stubtest-allowlist.txt names them for stubtest.

ReadingTuple = tuple[
    int,  # wall_ns: ns since the epoch
    bytes,  # raw: the 36 payload bytes
    float,  # voltage, V
    float,  # current, A
    float,  # power, W
    float,  # set_voltage, V
    float,  # set_current, A
    bool,  # output_on
    str,  # mode: off, cv, cc, held_above, unknown
    int,  # mode_raw
    str,  # mode_text
    str,  # live_mode: dc, program, pd, charge, unknown
    int,  # live_mode_raw
    int,  # faults: the fault word
    int,  # temperature, °C
    float,  # energy, Wh
    int,  # working_time, s
]
InfoTuple = tuple[str, str, str | None, bytes | None, str | None]
FoundTuple = tuple[str, str, str, str, int | None, bool | None, str]
CountersTuple = tuple[int, int, int]
EventTuple = tuple[int, str, dict[str, object]]
SentTuple = tuple[int, float, str, int, bytes]
Dispatch = Callable[[EventTuple], None]
StatePath = str | os.PathLike[str]

SCAN_DEFAULT_S: float
SCAN_MIN_S: float
SCAN_MAX_S: float
WAIT_SLICE_S: float
SUPPLY_MAX_RAW_VOLTAGE: int
SUPPLY_MAX_RAW_CURRENT: int
MOCK_HOST_ID: bytes

@final
class Session:
    @staticmethod
    def connect(
        identifier: str,
        state_dir: StatePath | None,
        reconnect: bool,
        max_voltage: float | None,
        max_current: float | None,
    ) -> Session: ...
    @staticmethod
    def from_mock(
        scripts: list[ScriptDict],
        state_dir: StatePath | None,
        reconnect: bool,
        max_voltage: float | None,
        max_current: float | None,
        identifier: str,
        handles: MockHandles,
    ) -> Session: ...
    def ready(self, dispatch: Dispatch | None) -> InfoTuple: ...
    def set_voltage(self, volts: float, dispatch: Dispatch | None) -> None: ...
    def set_current_limit(self, amps: float, dispatch: Dispatch | None) -> None: ...
    def request_remote_control(self, dispatch: Dispatch | None) -> None: ...
    def release_remote_control(self, dispatch: Dispatch | None) -> None: ...
    def output_on(self, dispatch: Dispatch | None) -> None: ...
    def output_off(self, dispatch: Dispatch | None) -> None: ...
    def close(self, output_off: bool, dispatch: Dispatch | None) -> None: ...
    def close_start(self, output_off: bool) -> None: ...
    def wait_feed(self, after: int, wait_s: float) -> int: ...
    def flush(self) -> None: ...
    def pump(self, dispatch: Dispatch | None) -> None: ...
    def info(self) -> InfoTuple | None: ...
    def latest_reading(self) -> ReadingTuple | None: ...
    def link_state(self) -> str: ...
    def remote_state(self) -> str: ...
    def identifier(self) -> str: ...
    def transport(self) -> str | None: ...
    def counters(self) -> CountersTuple | None: ...
    def dropped_readings(self) -> int: ...
    def feed_seq(self) -> int: ...
    def newest_reading(self) -> int: ...
    def readings_after(self, cursor: int, limit: int) -> tuple[list[ReadingTuple], int, int]: ...
    def events_take(self, limit: int) -> list[EventTuple]: ...
    def events_overwritten(self) -> int: ...
    def loss_text(self) -> str | None: ...
    def set_reconnect(self, on: bool) -> None: ...
    def set_limits(self, max_voltage: float | None, max_current: float | None) -> None: ...

@final
class MockHandles:
    def __new__(cls) -> MockHandles: ...
    def sent(self) -> list[SentTuple]: ...
    def closes(self) -> int: ...
    def attempts(self) -> int: ...

def discover(scan_time_s: float, bluetooth: bool, usb: bool) -> list[FoundTuple]: ...
def not_found_text() -> str: ...
def csv_header() -> str: ...
def format_csv_row(raw: bytes, wall_ns: int, origin_ns: int) -> str: ...
def raw_voltage(volts: float, max_voltage: float | None) -> int: ...
def raw_current(amps: float, max_current: float | None) -> int: ...
def setpoint_range_text(field: str, value: float, minimum: float, maximum: float) -> str: ...
def default_state_dir() -> Path: ...
def host_id(state_dir: StatePath | None) -> bytes: ...
def set_gate(level: int) -> None: ...
def log_wait(wait_s: float) -> None: ...
def log_test(target: str, level: int, message: str, count: int) -> None: ...
def pending_safety() -> list[str]: ...
def wait_safety(dispatch: Dispatch | None = None) -> None: ...
def fixtures() -> dict[str, bytes]: ...
def c3(output: int, model: int, charge_error: int, set_voltage: int, set_current: int) -> bytes: ...
def on_air(kind: str, opcode: int, payload: bytes) -> bytes: ...
def sample_events() -> list[EventTuple]: ...
