[package]
name = "mp305-py"
description = "Python bindings for mp305-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "mp305_py"
crate-type = ["cdylib", "rlib"]

[lints.rust]
unsafe_code = "deny"
missing_docs = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
missing_docs_in_private_items = "warn"

[dependencies]
mp305-core = { path = "../mp305-core" }
