#!/usr/bin/env python3
"""Generate docs/v-model/traceability.md and report traceability defects.

Reads the Parent, Mitigation and Verifies columns of the requirement and
test specification documents and, once code exists, the spec tags in the
code (`Test: UT-...` in Rust doc comments, `@pytest.mark.spec("...")` in
Python). The output file is committed and never edited by hand.

Usage: python3 scripts/check_traceability.py [--check]

--check writes nothing and exits with status 1 when the committed matrix is
out of date or a defect is found.
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VM = ROOT / "docs" / "v-model"
DOCS = {
    "ur": VM / "1-user-requirements.md",
    "sr": VM / "2-system-requirements.md",
    "st": VM / "7-system-tests.md",
    "at": VM / "8-acceptance-tests.md",
}
ID = re.compile(r"\b(H|UR|SR|AR|DD-[A-Z]+|AT|ST|IT|UT-[A-Z]+)-(\d{3})\b")


def rows(path):
    """Yield (header, cells) for every table row of a Markdown file."""
    header = None
    for line in path.read_text().splitlines():
        if not line.startswith("|"):
            header = None
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if header is None:
            header = cells
            continue
        if all(set(c) <= set("-: ") for c in cells):
            continue
        yield header, cells


def table(path, id_prefix):
    """Return {id: {column: value}} for rows whose first cell is an ID."""
    out = {}
    for header, cells in rows(path):
        if not cells or not re.fullmatch(rf"{id_prefix}-\d{{3}}", cells[0]):
            continue
        out[cells[0]] = dict(zip(header, cells))
    return out


def ids(text, prefix):
    return sorted({m.group(0) for m in ID.finditer(text) if m.group(1) == prefix})


def summary(text, limit=64):
    text = re.sub(r"`", "", text)
    first = re.split(r"(?<=[.;])\s", text, 1)[0]
    return first if len(first) <= limit else first[: limit - 3].rstrip() + "..."


def revision(path):
    last = None
    for _, cells in rows(path):
        if cells and cells[0].isdigit():
            last = cells[0]
    return last


def code_tags():
    """Spec IDs named by automated tests in the code, when code exists."""
    tags = {}
    for pattern, rx in (
        ("crates/**/*.rs", re.compile(r"Test:\s*((?:UT-[A-Z]+|IT|ST|AT)-\d{3})")),
        ("python/**/*.py", re.compile(r'spec\("((?:UT-[A-Z]+|IT|ST|AT)-\d{3})"\)')),
        ("tests/**/*.py", re.compile(r'spec\("((?:UT-[A-Z]+|IT|ST|AT)-\d{3})"\)')),
    ):
        for f in ROOT.glob(pattern):
            for m in rx.finditer(f.read_text(errors="ignore")):
                tags.setdefault(m.group(1), set()).add(str(f.relative_to(ROOT)))
    return tags


def build():
    hazards = table(DOCS["ur"], "H")
    urs = table(DOCS["ur"], "UR")
    srs = table(DOCS["sr"], "SR")
    sts = table(DOCS["st"], "ST")
    ats = table(DOCS["at"], "AT")
    tags = code_tags()
    defects = []

    at_for = {}
    for at, r in ats.items():
        for ur in ids(r.get("Verifies", ""), "UR"):
            at_for.setdefault(ur, []).append(at)
    st_for = {}
    for st, r in sts.items():
        for sr in ids(r.get("Verifies", ""), "SR"):
            st_for.setdefault(sr, []).append(st)

    lines = [
        "# Traceability matrix",
        "",
        "Generated by `scripts/check_traceability.py` on "
        f"{datetime.date.today().isoformat()} from 1-user-requirements.md revision "
        f"{revision(DOCS['ur'])}, 2-system-requirements.md revision {revision(DOCS['sr'])}, "
        f"7-system-tests.md revision {revision(DOCS['st'])} and 8-acceptance-tests.md "
        f"revision {revision(DOCS['at'])}. Do not edit by hand.",
        "",
        "## 1. Hazards",
        "",
        "| Hazard | Summary | Mitigating URs | Mitigating SRs (draft) | Verifying ATs |",
        "|---|---|---|---|---|",
    ]
    for h, r in hazards.items():
        h_urs = ids(r.get("Mitigation", ""), "UR")
        h_srs = sorted(
            sr for sr, s in srs.items()
            if h in ids(s.get("Parent or source", ""), "H")
            or set(ids(s.get("Parent or source", ""), "UR")) & set(h_urs)
        )
        h_ats = sorted({at for ur in h_urs for at in at_for.get(ur, [])})
        if not h_urs:
            defects.append(f"{h} has no mitigating UR")
        lines.append(
            f"| {h} | {summary(r.get('Hazard', ''))} | {', '.join(h_urs) or 'none'} | "
            f"{', '.join(h_srs) or 'none'} | {', '.join(h_ats) or 'none'} |"
        )

    lines += ["", "## 2. User requirements", "", "| UR | Summary | Parent or source | Verified by | Status |", "|---|---|---|---|---|"]
    for ur, r in urs.items():
        v = at_for.get(ur, [])
        if not v:
            defects.append(f"{ur} has no acceptance test")
        lines.append(
            f"| {ur} | {summary(r.get('Requirement', ''))} | {r.get('Parent or source', '')} | "
            f"{', '.join(v) or 'none'} | {r.get('Status', '')} |"
        )

    lines += ["", "## 3. System requirements", "", "| SR | Parent or source | Verified by | Status |", "|---|---|---|---|"]
    for sr, r in srs.items():
        v = st_for.get(sr, [])
        if not v:
            defects.append(f"{sr} has no system test")
        for parent in ids(r.get("Parent or source", ""), "UR"):
            if parent not in urs:
                defects.append(f"{sr} names unknown parent {parent}")
        lines.append(f"| {sr} | {r.get('Parent or source', '')} | {', '.join(v) or 'none'} | {r.get('Status', '')} |")

    lines += ["", "## 4. Test specifications", "", "| Test | Verifies | Implemented by |", "|---|---|---|"]
    for t, r in list(ats.items()) + list(sts.items()):
        impl = ", ".join(sorted(tags.get(t, []))) or "no code yet"
        for x in ids(r.get("Verifies", ""), "UR") + ids(r.get("Verifies", ""), "SR"):
            if x not in urs and x not in srs:
                defects.append(f"{t} verifies unknown item {x}")
        lines.append(f"| {t} | {r.get('Verifies', '')} | {impl} |")
    for tag in tags:
        if tag not in ats and tag not in sts:
            defects.append(f"code names test {tag}, which has no specification entry")

    lines += ["", "## 5. Defects", ""]
    lines += [f"- {d}" for d in defects] if defects else ["None."]
    return "\n".join(lines) + "\n", defects


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text, defects = build()
    out = VM / "traceability.md"
    if args.check:
        current = out.read_text() if out.exists() else ""
        stale = re.sub(r"on \d{4}-\d{2}-\d{2}", "", current) != re.sub(r"on \d{4}-\d{2}-\d{2}", "", text)
        if stale:
            print("traceability.md is out of date; run scripts/check_traceability.py")
        for d in defects:
            print("defect:", d)
        sys.exit(1 if stale or defects else 0)
    out.write_text(text)
    print(f"wrote {out.relative_to(ROOT)}; {len(defects)} defect(s)")
    for d in defects:
        print("defect:", d)


if __name__ == "__main__":
    main()
